import '../styles/globals.css';
import {Provider} from "react-redux"
import Script from 'next/script'
import { NextUIProvider } from '@nextui-org/react';
import Head from 'next/head';
import store from '../redux/store';



function MyApp({ Component, pageProps }) {
  return (
   <div>
      <Head>
      <title>Office Room</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
         
      </Head>
      <Provider store={store}>
            <NextUIProvider>
               <Component {...pageProps} />
            </NextUIProvider>
      </Provider>
      <Script
       src="https://cdn.tailwindcss.com"
      strategy="beforeInteractive"
      /> 
</div>
    
  )
}

export default MyApp
