import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { getEmployeeData } from '../redux/employee/employeeInfoSlice';




export default function Home() {
   const dispatch=useDispatch()


   useEffect(()=>{
      dispatch(getEmployeeData())
   })

  return (
    <div>
      <Head>
        <title>Office Room</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
       {/* <Chat/> */}
       <h1>Home page</h1>
    </div>
  )
}
